import { EDispositionRemarkFor } from '../model/dispositionRemark';
import { EStaffType } from '../types/tempEmpanelment';

export const qualificationMasterData = [
  {
    name: 'MBBS',
    displayName: 'MBBS (Bachelor of Medicine, Bachelor of Surgery)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.MBBS,
  },
  {
    name: 'BAMS',
    displayName: 'BAMS (Bachelor of Ayurvedic Medicine and Surgery)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.MBBS,
  },
  {
    name: 'BHMS',
    displayName: 'BHMS (Bachelor of Homeopathic Medicine and Surgery)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.MBBS,
  },
  {
    name: 'BUMS',
    displayName: 'BUMS (Bachelor of Unani Medicine and Surgery)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.MBBS,
  },
  {
    name: 'BNYS',
    displayName: 'BNYS (Bachelor of Naturopathy and Yogic Sciences)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.MBBS,
  },
  {
    name: 'BDS',
    displayName: 'BDS (Bachelor of Dental Surgery)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'MD',
    displayName: 'MD (Doctor of Medicine)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'MS',
    displayName: 'MS (Master of Surgery)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'DNB',
    displayName: 'DNB (Diplomate of National Board)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'MDS',
    displayName: 'MDS (Master of Dental Surgery)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'DM',
    displayName: 'DM (Doctorate of Medicine)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'MCh',
    displayName: 'MCh (Master of Chirurgiae)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'DGO',
    displayName: 'DGO (Diploma in Gynecology and Obstetrics)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Gynecologist,
  },
  {
    name: 'DCH',
    displayName: 'DCH (Diploma in Child Health)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'DA',
    displayName: 'DA (Diploma in Anesthesiology)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'DLO',
    displayName: 'DLO (Diploma in Otorhinolaryngology)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'DO',
    displayName: 'DO (Diploma in Ophthalmology)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'DOrtho',
    displayName: 'D.Ortho (Diploma in Orthopedics)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'DPM',
    displayName: 'DPM (Diploma in Psychological Medicine)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'PhD',
    displayName: 'Ph.D. (Doctor of Philosophy)',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'Fellowship',
    displayName: 'Fellowship',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Pathologist,
  },
  {
    name: 'Other',
    displayName: 'Other',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.MBBS,
  },
  // Additional data for Cardiologist
  {
    name: 'Fellowship in Cardiology',
    displayName: 'Fellowship in Cardiology',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Cardiologist,
  },
  {
    name: 'Diploma in Cardiology',
    displayName: 'Diploma in Cardiology',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Cardiologist,
  },
  // Additional data for Radiologist
  {
    name: 'Fellowship in Radiology',
    displayName: 'Fellowship in Radiology',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Radiologist,
  },
  {
    name: 'Diploma in Radiology',
    displayName: 'Diploma in Radiology',
    isActive: true,
    isDeleted: false,
    staffType: EStaffType.Radiologist,
  },
];

export const councilMasterData = [
  { name: 'MCI', displayName: 'Medical Council of India', isActive: true, isDeleted: false },
  { name: 'DCI', displayName: 'Dental Council of India', isActive: true, isDeleted: false },
  { name: 'NMC', displayName: 'National Medical Commission', isActive: true, isDeleted: false },
  { name: 'INC', displayName: 'Indian Nursing Council', isActive: true, isDeleted: false },
  { name: 'PCI', displayName: 'Pharmacy Council of India', isActive: true, isDeleted: false },
  {
    name: 'CCIM',
    displayName: 'Central Council of Indian Medicine',
    isActive: true,
    isDeleted: false,
  },
  { name: 'CCH', displayName: 'Central Council of Homeopathy', isActive: true, isDeleted: false },
  { name: 'COC', displayName: 'Central Council of Homeopathy', isActive: true, isDeleted: false },
  {
    name: 'BOG',
    displayName: 'Board of Governors in Supersession of the MCI',
    isActive: true,
    isDeleted: false,
  },
  { name: 'NBE', displayName: 'National Board of Examinations', isActive: true, isDeleted: false },
  { name: 'Other', displayName: 'Other', isActive: true, isDeleted: false },
];

export const ownershipTypeMasterData = [
  {
    name: 'Sole Proprietorship',
    displayName: 'Sole Proprietorship',
    isActive: true,
    isDeleted: false,
  },
  { name: 'LLP/Partnership', displayName: 'LLP/Partnership', isActive: true, isDeleted: false },
  { name: 'Private Limited', displayName: 'Private Limited', isActive: true, isDeleted: false },
];

export const insuranceCompanyData = [
  { name: 'HDFC', displayName: 'HDFC', isActive: true, isDeleted: false },
  { name: 'IPRU', displayName: 'IPRU', isActive: true, isDeleted: false },
  { name: 'Max Life', displayName: 'Max Life', isActive: true, isDeleted: false },
  { name: 'Reliance', displayName: 'Reliance', isActive: true, isDeleted: false },
  { name: 'RS', displayName: 'RS', isActive: true, isDeleted: false },
  { name: 'SBI', displayName: 'SBI', isActive: true, isDeleted: false },
];

export const testsWithCategory = [
  {
    group: 'Urine',
    tests: [
      {
        group: 'Urine',
        code: '2 urine dipstick',
        name: '2 Urine dipstick',
        loincCode: '50556-0',
      },
      {
        group: 'Urine',
        code: 'Chlorides',
        name: 'Chloride [Moles/volume] in Urine',
        loincCode: '2078-4',
      },
      {
        group: 'Urine',
        code: 'MSU',
        name: 'Microscopic Urine Analysis',
        loincCode: '53315-8',
      },
      {
        group: 'Urine',
        code: 'RUA',
        name: 'Routine Urine Analysis (RUA)',
        loincCode: '24356-8',
      },
      {
        group: 'Urine',
        code: 'Urine COTININE Qualitative',
        name: 'Urine COTININE Qualitative',
        loincCode: 'LP14564-6',
      },
      {
        group: 'Urine',
        code: 'Urine COTININE Quantitave',
        name: 'Urine COTININE Quantitave',
        loincCode: '10366-3',
      },
    ],
  },
  {
    group: 'Cardiology',
    tests: [
      {
        group: 'Cardiology',
        code: '2DD',
        name: '2-D ECHO With Colour Doppler',
        loincCode: '34552-0',
      },
      {
        group: 'Cardiology',
        code: 'CRA',
        name: 'CRA(Home Visit TMT)',
        loincCode: 'need to check',
      },
      {
        group: 'Cardiology',
        code: 'Dobutamine',
        name: 'Dobutamine Stress Echo',
        loincCode: '93352',
      },
      {
        group: 'Cardiology',
        code: 'ECG',
        name: 'ECG',
        loincCode: '11524-6',
      },
      {
        group: 'Cardiology',
        code: 'TMT',
        name: 'TMT (Tread Mill Test) - Computerised Treadmill Test',
        loincCode: '18752-6',
      },
    ],
  },
  {
    group: 'Biochemistry',
    tests: [
      {
        group: 'Biochemistry',
        code: 'ABO & Rh',
        name: 'ABO & Rh (Blood Group & RJi Factor)',
        loincCode: '93916-5',
      },
      {
        group: 'Biochemistry',
        code: 'AEC',
        name: 'AEC (Absolute Eosinophil Count)',
        loincCode: '712-0',
      },
      {
        group: 'Biochemistry',
        code: 'AFP',
        name: 'AFP (Alpha Fetoprotein)',
        loincCode: '48802-3',
      },
      {
        group: 'Biochemistry',
        code: 'LIP',
        name: 'Lipid Profile (Total Cholesterol, HDL B190, Triglycerides, LDL Cholesterol, VLDL Cholesterol)',
        loincCode: 'NA',
      },
      {
        group: 'Biochemistry',
        code: 'Albumin',
        name: 'Albumin',
        loincCode: '1751-7',
      },
      {
        group: 'Biochemistry',
        code: 'ALP',
        name: 'Alk Phosphates',
        loincCode: '6768-6',
      },
      {
        group: 'Biochemistry',
        code: 'Amylase',
        name: 'Amylase - Serum',
        loincCode: '1798-8',
      },
      {
        group: 'Biochemistry',
        code: 'Anti HCV',
        name: 'Anti HCV (IgG) (HCV Antibodies)',
        loincCode: '75886-2',
      },
      {
        group: 'Biochemistry',
        code: 'APTT',
        name: 'APTT (Activated Partial Thromboplastin Time)',
        loincCode: '52767-1',
      },
      {
        group: 'Biochemistry',
        code: 'Bilirubin (Direct / Conjugated)',
        name: 'Bilirubin (Direct / Conjugated)',
        loincCode: '14629-0',
      },
      {
        group: 'Biochemistry',
        code: 'Bilirubin (Indirect / Unconjugated)',
        name: 'Bilirubin (Indirect / Unconjugated)',
        loincCode: '14630-8',
      },
      {
        group: 'Biochemistry',
        code: 'Bilirubin (Total)',
        name: 'Bilirubin (Total)',
        loincCode: '14631-6',
      },
      {
        group: 'Biochemistry',
        code: 'Serum Billirubin',
        name: 'Serum Bilirubin',
        loincCode: '14631-6',
      },
      {
        group: 'Biochemistry',
        code: 'Blood smear finding [Identifier] in Blood by Light microscopy',
        name: 'Blood smear finding [Identifier] in Blood by Light microscopy',
        loincCode: '5909-7',
      },
      {
        group: 'Biochemistry',
        code: 'BUN',
        name: 'Blood Urea Nitrogen',
        loincCode: '3094-0',
      },
      {
        group: 'Biochemistry',
        code: 'BST',
        name: 'BST(Blood Sugar Tolerance)',
        loincCode: '21004-7',
      },
      {
        group: 'Biochemistry',
        code: 'Calcium',
        name: 'Calcium',
        loincCode: '17861-6',
      },
      {
        group: 'Biochemistry',
        code: 'CA 125',
        name: 'Cancer Antigen 125 (CA 125), Serum or Plasma',
        loincCode: '10334-1',
      },
      {
        group: 'Biochemistry',
        code: 'CBC',
        name: 'CBC (Complete Blood Count)',
        loincCode: '58410-2',
      },
      {
        group: 'Biochemistry',
        code: 'CBC+ESR',
        name: 'CBC panel - Blood by Automated count + Erythrocyte sedimentation rate',
        loincCode: '57782-5; 30341-2',
      },
      {
        group: 'Biochemistry',
        code: 'Cholesterol',
        name: 'Cholesterol',
        loincCode: '2093-3',
      },
      {
        group: 'Biochemistry',
        code: 'Cholesterol in HDL/LDL',
        name: 'Cholesterol in HDL/Cholesterol in LDL [Mass Ratio] in Serum or Plasma',
        loincCode: '16616-5',
      },
      {
        group: 'Biochemistry',
        code: 'Copper',
        name: 'Copper',
        loincCode: '5631-7',
      },
      {
        group: 'Biochemistry',
        code: 'CRP',
        name: 'CRP (C-Reactive Protein) - C reactive protein [Presence] in Serum or Plasma',
        loincCode: '11039-5',
      },
      {
        group: 'Biochemistry',
        code: 'CT',
        name: 'CT (Clotting Time) - BT / CT (Bleeding Time / Clotting Time)',
        loincCode: '3184-9',
      },
      {
        group: 'Biochemistry',
        code: 'DLC',
        name: 'DLC (Differential Leucocyte Count) - Leukocytes [#/volume] in Blood',
        loincCode: '26464-8',
      },
      {
        group: 'Biochemistry',
        code: 'Electrolytes',
        name: 'Electrolytes panel - Blood - Electrolytes (Sodium, Potassium and Chloride)',
        loincCode: '55231-5',
      },
      {
        group: 'Biochemistry',
        code: 'ESR',
        name: 'ESR',
        loincCode: '30341-2',
      },
      {
        group: 'Biochemistry',
        code: 'FBS',
        name: 'Fasting Blood Sugar',
        loincCode: '1558-6',
      },
      {
        group: 'Biochemistry',
        code: 'Ferritin',
        name: 'Ferritin [Mass/volume] in Serum or Plasma',
        loincCode: '2276-4',
      },
      {
        group: 'Biochemistry',
        code: 'FSH ',
        name: 'FSH (Follicle Stimulating Hormone)',
        loincCode: '15067-2',
      },
      {
        group: 'Biochemistry',
        code: 'G6PD',
        name: 'G6PD -Quantitative (G-6 Phosphatedehydrogenase)',
        loincCode: '2359-8',
      },
      {
        group: 'Biochemistry',
        code: 'GGTP',
        name: 'GGTP (Gamma Glutamyl Tran Peptidase)',
        loincCode: '2324-2',
      },
      {
        group: 'Biochemistry',
        code: 'RBS',
        name: 'Glucose [Mass/volume] in Serum or Plasma',
        loincCode: '2345-7',
      },
      {
        group: 'Biochemistry',
        code: 'Post Prandial Blood Sugar - PPBS',
        name: 'Glucose [Mass/volume] in Serum or Plasma --2 hours post meal',
        loincCode: '1521-4',
      },
      {
        group: 'Biochemistry',
        code: 'Glucose tolerance [Interpretation] in Serum or Plasma',
        name: 'Glucose tolerance [Interpretation] in Serum or Plasma',
        loincCode: '21004-7',
      },
      {
        group: 'Biochemistry',
        code: 'Glucose tolerance 2 hours panel - Serum or Plasma',
        name: 'Glucose tolerance 2 hours panel - Serum or Plasma',
        loincCode: '72171-2',
      },
      {
        group: 'Biochemistry',
        code: 'Haemogram ',
        name: 'Haemogram (without peripheral smear)',
        loincCode: '24317-0',
      },
      {
        group: 'Biochemistry',
        code: 'HBA1c',
        name: 'HBA1c',
        loincCode: '4548-4',
      },
      {
        group: 'Biochemistry',
        code: 'HBDH',
        name: 'HBDH (Hydroxy Butyrate DeHydro) - Beta hydroxybutyrate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma',
        loincCode: '1682-4',
      },
      {
        group: 'Biochemistry',
        code: 'Hbeag',
        name: 'Hbeag',
        loincCode: '13954-3',
      },
      {
        group: 'Biochemistry',
        code: 'HbsAg',
        name: 'HbsAg - Australia Antigen Test(Hepatitis B)',
        loincCode: '70154-0',
      },
      {
        group: 'Biochemistry',
        code: 'HCV',
        name: 'HCV(Hepatitis C Virus)',
        loincCode: '16128-1',
      },
      {
        group: 'Biochemistry',
        code: 'HDL Cholesterol',
        name: 'HDL Cholesterol',
        loincCode: '2085-9',
      },
      {
        group: 'Biochemistry',
        code: 'Hematocrit',
        name: 'Hematocrit [Volume Fraction] of Blood',
        loincCode: '20570-8',
      },
      {
        group: 'Biochemistry',
        code: 'Hemoglobin',
        name: 'Hemoglobin [Mass/volume] in Blood',
        loincCode: '718-7',
      },
      {
        group: 'Biochemistry',
        code: 'HIV',
        name: 'HIV1 & HIV2 By ELISA+B60 Method',
        loincCode: '89365-1',
      },
      {
        group: 'Biochemistry',
        code: 'Iron / TIBC',
        name: 'Iron / TIBC',
        loincCode: '50190-8',
      },
      {
        group: 'Biochemistry',
        code: 'KFT/RFT',
        name: 'KFT (Kidney function test)/Renal function test)',
        loincCode: '24362-6',
      },
      {
        group: 'Biochemistry',
        code: 'LDH',
        name: 'LDH',
        loincCode: '2532-0',
      },
      {
        group: 'Biochemistry',
        code: 'LDL ',
        name: 'LDL (Low Density Lipids Cholesterol)',
        loincCode: '2089-1',
      },
      {
        group: 'Biochemistry',
        code: 'LFT',
        name: 'Liver Function Test',
        loincCode: '24325-3',
      },
      {
        group: 'Biochemistry',
        code: 'MCH ',
        name: 'MCH (Mean Corpuscular Haemoglobin)',
        loincCode: '28539-5',
      },
      {
        group: 'Biochemistry',
        code: 'MCV ',
        name: 'MCV (Mean Corpuscular Volume)',
        loincCode: '787-2',
      },
      {
        group: 'Biochemistry',
        code: 'Mg(Magnesium)',
        name: 'Mg(Magnesium)',
        loincCode: '2601-3',
      },
      {
        group: 'Biochemistry',
        code: 'Microalbumin',
        name: 'Microalbumin(Urine)',
        loincCode: '14957-5',
      },
      {
        group: 'Biochemistry',
        code: 'Phosphate',
        name: 'Phosphate [Mass/volume] in Serum or Plasma',
        loincCode: '2777-1',
      },
      {
        group: 'Biochemistry',
        code: 'Platelets',
        name: 'Platelets [#/volume] in Blood by Automated count',
        loincCode: '777-3',
      },
      {
        group: 'Biochemistry',
        code: 'Potassium',
        name: 'Potassium [Moles/volume] in Serum or Plasma',
        loincCode: '2823-3',
      },
      {
        group: 'Biochemistry',
        code: 'Protein electrophoresis panel',
        name: 'Protein electrophoresis panel - Serum or Plasma',
        loincCode: '24351-9',
      },
      {
        group: 'Biochemistry',
        code: 'Proteins (Albumin)',
        name: 'Proteins (Albumin)',
        loincCode: '1751-7',
      },
      {
        group: 'Biochemistry',
        code: 'Proteins (Total)',
        name: 'Proteins (Total)',
        loincCode: 'LP32144-5',
      },
      {
        group: 'Biochemistry',
        code: 'Proteins(Globulin)',
        name: 'Proteins(Globulin)',
        loincCode: '2336-6',
      },
      {
        group: 'Biochemistry',
        code: 'Prothrombin Time (APTT)',
        name: 'Prothrombin Time (APTT)',
        loincCode: '5902-2',
      },
      {
        group: 'Biochemistry',
        code: 'PSA ',
        name: 'PSA (Prostrate Specific Antigen)',
        loincCode: '10886-0',
      },
      {
        group: 'Biochemistry',
        code: 'RBC ',
        name: 'RBC (Red Blood Cells)',
        loincCode: '789-8',
      },
      {
        group: 'Biochemistry',
        code: 'Rheumatoid arthritis disease activity panel',
        name: 'Rheumatoid arthritis disease activity panel - Serum or Plasma by VectraDA',
        loincCode: '75635-3',
      },
      {
        group: 'Biochemistry',
        code: 'Serum Acid Phospatase',
        name: 'Serum Acid Phospatase',
        loincCode: '1715-2',
      },
      {
        group: 'Biochemistry',
        code: 'Serum Albumin',
        name: 'Serum Albumin',
        loincCode: '1751-7',
      },
      {
        group: 'Biochemistry',
        code: 'Serum Amylase',
        name: 'Serum Amylase',
        loincCode: '1798-8',
      },
      {
        group: 'Biochemistry',
        code: 'Serum CPK ',
        name: 'Serum CPK (Creatinine Phosphokinase)',
        loincCode: '2157-6',
      },
      {
        group: 'Biochemistry',
        code: 'Serum Creatinine',
        name: 'Serum Creatinine',
        loincCode: '2160-0',
      },
      {
        group: 'Biochemistry',
        code: 'Serum LH ',
        name: 'Serum LH (Luetenizing Hormone)',
        loincCode: '10501-5',
      },
      {
        group: 'Biochemistry',
        code: 'Serum Lipase',
        name: 'Serum Lipase',
        loincCode: '3040-3',
      },
      {
        group: 'Biochemistry',
        code: 'Serum Nicotine/Cotinine',
        name: 'Serum Nicotine/Cotinine',
        loincCode: '59645-2',
      },
      {
        group: 'Biochemistry',
        code: 'Serum Triglycerides',
        name: 'Serum Triglycerides',
        loincCode: '2571-8',
      },
      {
        group: 'Biochemistry',
        code: 'Serum/Blood Cotinine',
        name: 'Serum/Blood Cotinine',
        loincCode: '59645-2',
      },
      {
        group: 'Biochemistry',
        code: 'SGOT',
        name: 'SGOT/AST',
        loincCode: '1920-8',
      },
      {
        group: 'Biochemistry',
        code: 'SGPT',
        name: 'SGPT / ALT',
        loincCode: '1742-6',
      },
      {
        group: 'Biochemistry',
        code: 'SMA-12',
        name: 'SMA12 - Total cholesterol, HDL, LDL, Total cholesterol / HDL ratio, TG, FBS, SGOT, SGPT, GGT, Serum Bilirubin total, Serum Bilirubin Direct, Serum Bilirubin indirect, Total protein, Albumin, Globulin, A/G ratio, Serum Creatinine, alkaline phosphatase',
        loincCode: 'SMA12-IP',
      },
      {
        group: 'Biochemistry',
        code: 'SMA-13',
        name: 'SMA13 - Total cholesterol, HDL, LDL, Total cholesterol / HDL ratio, TG, RBS, SGOT, SGPT, GGT, Serum Bilirubin total, Serum Bilirubin Direct, Serum Bilirubin indirect, Total protein, Albumin, Globulin, A/G ratio, Serum Creatinine, alkaline phosphatase',
        loincCode: 'SMA12-IP',
      },
      {
        group: 'Biochemistry',
        code: 'Sodium',
        name: 'Sodium',
        loincCode: '2951-2',
      },
      {
        group: 'Biochemistry',
        code: 'T3',
        name: 'T3 (Triiodothyronine)',
        loincCode: '#N/A',
      },
      {
        group: 'Biochemistry',
        code: 'T4 (Thyroxine)',
        name: 'T4 (Thyroxine)',
        loincCode: '3026-2',
      },
      {
        group: 'Biochemistry',
        code: 'TFT',
        name: 'Thyroid Profile as a package is not there in code, hence use combination of T3,T4 & TSH',
        loincCode: 'ALTFT-3',
      },
      {
        group: 'Biochemistry',
        code: 'TLC',
        name: 'Total Leucocyte Count(TLC)',
        loincCode: '6690-2',
      },
      {
        group: 'Biochemistry',
        code: 'Triglycerides',
        name: 'Triglycerides',
        loincCode: '3043-7',
      },
      {
        group: 'Biochemistry',
        code: 'TSH ',
        name: 'TSH (Thyroid Stimulating Hormone)',
        loincCode: '90224-7',
      },
      {
        group: 'Biochemistry',
        code: 'Urea nitrogen [Mass/volume] in Serum or Plasma ',
        name: 'Urea nitrogen [Mass/volume] in Serum or Plasma (Blood Urea)',
        loincCode: '3094-0',
      },
      {
        group: 'Biochemistry',
        code: 'Urea nitrogen [Mass/volume] in Serum or Plasma ',
        name: 'Urea nitrogen [Mass/volume] in Serum or Plasma (Urea)',
        loincCode: '3094-0',
      },
      {
        group: 'Biochemistry',
        code: 'Uric Acid / Serum Uric Acid',
        name: 'Uric Acid / Serum Uric Acid',
        loincCode: '3084-1',
      },
      {
        group: 'Biochemistry',
        code: 'VDRL ',
        name: 'VDRL (Venereal Disease Research Laboratory)',
        loincCode: '14904-7',
      },
      {
        group: 'Biochemistry',
        code: 'VLDL',
        name: 'VLDL (Very Low Density Lipids)',
        loincCode: '13458-5',
      },
      {
        group: 'Biochemistry',
        code: 'WBC',
        name: 'WBC(White Blood Cells)',
        loincCode: '6690-2',
      },
      {
        group: 'Biochemistry',
        code: 'Widal ',
        name: 'Widal (Tube Method)',
        loincCode: '13284-5',
      },
    ],
  },
  {
    group: 'Radiology',
    tests: [
      {
        group: 'Radiology',
        code: 'CXR',
        name: 'Chest X-Ray',
        loincCode: '71010',
      },
      {
        group: 'Radiology',
        code: 'KUB - Ultrasound',
        name: 'KUB (Kidney, Urinary Bladder) - Ultrasound, retroperitoneal',
        loincCode: '76775',
      },
      {
        group: 'Radiology',
        code: 'MG Breast Screening',
        name: 'MG Breast Screening',
        loincCode: '24606-6',
      },
      {
        group: 'Radiology',
        code: 'Radiologic examination, chest; single view, frontal',
        name: 'Radiologic examination, chest; single view, frontal',
        loincCode: '71010',
      },
      {
        group: 'Radiology',
        code: 'SONO. KIDNEY URETER & BLADDER',
        name: 'SONO. KIDNEY URETER & BLADDER',
        loincCode: '76775',
      },
      {
        group: 'Radiology',
        code: 'Stress Thalium',
        name: 'Stress Thalium',
        loincCode: '82654-5',
      },
      {
        group: 'Radiology',
        code: 'USG',
        name: 'USG - Abdomen (Ultra Sonography - Abdomen)',
        loincCode: '#N/A',
      },
      {
        group: 'Radiology',
        code: 'Ultrasound Pelvis',
        name: 'Ultrasound Pelvis',
        loincCode: '#N/A',
      },
      {
        group: 'Radiology',
        code: 'Ultrasound Thyroid',
        name: 'Ultrasound Thyroid',
        loincCode: '76536',
      },
      {
        group: 'Radiology',
        code: 'Ultrasound, pelvic ',
        name: 'Ultrasound, pelvic (nonobstetric), real time with image documentation; complete',
        loincCode: '76856',
      },
      {
        group: 'Radiology',
        code: 'Ultrasound, retroperitoneal ',
        name: 'Ultrasound, retroperitoneal (eg, renal, aorta, nodes), real time with image documentation; limited',
        loincCode: '76775',
      },
      {
        group: 'Radiology',
        code: 'US Breast - bilateral',
        name: 'US Breast - bilateral',
        loincCode: '26214-7',
      },
      {
        group: 'Radiology',
        code: 'USG - Whole Abdomen(KUB)',
        name: 'USG - Whole Abdomen(KUB)',
        loincCode: '#N/A',
      },
      {
        group: 'Radiology',
        code: 'USG Abdomen+Pelvis',
        name: 'USG Abdomen+Pelvis',
        loincCode: '76700+76856',
      },
      {
        group: 'Radiology',
        code: 'XR Shoulder - bilateral Views',
        name: 'XR Shoulder - bilateral Views',
        loincCode: '26157-8',
      },
      {
        group: 'Radiology',
        code: 'X-Ray (Barium Enema)',
        name: 'X-Ray (Barium Enema)',
        loincCode: '74270',
      },
      {
        group: 'Radiology',
        code: 'X-Ray (Barium Swallow)',
        name: 'X-Ray (Barium Swallow)',
        loincCode: '74220',
      },
      {
        group: 'Radiology',
        code: 'X-Ray (Cholecystography)',
        name: 'X-Ray (Cholecystography)',
        loincCode: '36001-6',
      },
      {
        group: 'Radiology',
        code: 'X-Ray (Kidney Urinary Bladder)',
        name: 'X-Ray (Kidney Urinary Bladder)',
        loincCode: '74018',
      },
      {
        group: 'Radiology',
        code: 'X-ray (Lumbo-Sacral)',
        name: 'X-ray (Lumbo-Sacral)',
        loincCode: '72100',
      },
      {
        group: 'Radiology',
        code: 'X-Ray Abdomen KUB 1 view',
        name: 'X-Ray Abdomen KUB 1 view',
        loincCode: '74018',
      },
      {
        group: 'Radiology',
        code: 'X-Ray Abdomen/GUT(2 Plates)',
        name: 'X-Ray Abdomen/GUT(2 Plates)',
        loincCode: '74020',
      },
      {
        group: 'Radiology',
        code: 'X-Ray Abdomen/GUT(Plate 1)',
        name: 'X-Ray Abdomen/GUT(Plate 1)',
        loincCode: '74000',
      },
      {
        group: 'Radiology',
        code: 'X-Ray Dorsal Spine',
        name: 'X-Ray Dorsal Spine',
        loincCode: '72080',
      },
      {
        group: 'Radiology',
        code: 'X-Ray Hip/Other Joints',
        name: 'X-Ray Hip/Other Joints',
        loincCode: '73510',
      },
      {
        group: 'Radiology',
        code: 'X-ray KUB',
        name: 'X-ray KUB',
        loincCode: '76775',
      },
    ],
  },
  {
    group: 'Additional Services',
    tests: [
      {
        group: 'Additional Services',
        code: 'CHM',
        name: 'Child MER',
        loincCode: 'CMER-IP',
      },
      {
        group: 'Additional Services',
        code: 'DEXA Bone Densitometry',
        name: 'DEXA Bone Densitometry - Bone density quantitative measurement by DXA panel',
        loincCode: '83311-1',
      },
      {
        group: 'Additional Services',
        code: 'Digitization Data',
        name: 'Digitization Data',
        loincCode: 'NA',
      },
      {
        group: 'Additional Services',
        code: 'Fundoscopy',
        name: 'Fundoscopy',
        loincCode: 'LP149841-1',
      },
      {
        group: 'Additional Services',
        code: 'GEO',
        name: 'GEO Location',
        loincCode: 'NA',
      },
      {
        group: 'Additional Services',
        code: 'Home Visit ECG Technician',
        name: 'Home Visit ECG Technician',
        loincCode: 'HVET-SBIL',
      },
      {
        group: 'Additional Services',
        code: 'Home Visit Physician',
        name: 'Home Visit Physician',
        loincCode: 'HVP-SBIL',
      },
      {
        group: 'Additional Services',
        code: 'Home Visit Technician',
        name: 'Home Visit Technician',
        loincCode: 'HMT-SBIL',
      },
      {
        group: 'Additional Services',
        code: 'JMR',
        name: 'JMR (Juveline Medical Report)',
        loincCode: 'JMR-TATA',
      },
      {
        group: 'Additional Services',
        code: 'Mantoux Test / Tuberculin Test',
        name: 'Mantoux Test / Tuberculin Test',
        loincCode: '39263-9',
      },
      {
        group: 'Additional Services',
        code: 'MER',
        name: 'Medical Examination Report (MER)',
        loincCode: 'MER-IP',
      },
      {
        group: 'Additional Services',
        code: 'No Photo',
        name: 'No Photo',
        loincCode: 'NA',
      },
      {
        group: 'Additional Services',
        code: 'Pap smear tests',
        name: 'Pap smear tests - FPAR 2.0 set',
        loincCode: '86662-4',
      },
      {
        group: 'Additional Services',
        code: 'Photograph',
        name: 'Photograph',
        loincCode: 'NA',
      },
      {
        group: 'Additional Services',
        code: 'PFT',
        name: 'Pulmonary function test panel',
        loincCode: '81459-0',
      },
      {
        group: 'Additional Services',
        code: 'Pure tone threshold audiometry panel',
        name: 'Pure tone threshold audiometry panel',
        loincCode: '89015-2',
      },
      {
        group: 'Additional Services',
        code: 'Videography (Consider under mer cost)',
        name: 'Videography (Consider under mer cost)',
        loincCode: 'NA',
      },
    ],
  },
  {
    group: 'Fluid',
    tests: [
      {
        group: 'Fluid',
        code: 'Nicotine Sample Collection',
        name: 'Nicotine Sample Collection',
        loincCode: 'NA',
      },
      {
        group: 'Fluid',
        code: 'Sputum Routine',
        name: 'Sputum Routine',
        loincCode: '33455-7',
      },
      {
        group: 'Fluid',
        code: 'Stool Routine',
        name: 'Stool Routine',
        loincCode: '88847-9',
      },
    ],
  },
];

export const dispositionRemarkData = [
  {
    name: 'remark for deactivate provider',
    displayName: 'remark for deactivate provider',
    isActive: true,
    isDeleted: false,
    forType: EDispositionRemarkFor.Deactivate,
  },
  {
    name: 'remark for activate provider',
    displayName: 'remark for activate provider',
    isActive: true,
    isDeleted: false,
    forType: EDispositionRemarkFor.Activate,
  },
  {
    name: 'remark for delist provider',
    displayName: 'remark for delist provider',
    isActive: true,
    isDeleted: false,
    forType: EDispositionRemarkFor.Delist,
  },
];
